Repository effekt-lang/effekt, pull requests merged in 2024-06, with the labels that each got.

#478 Bugfix: Duplicate definitions in test stdlib
  effekt/jvm/src/test/scala/effekt/StdlibTests.scala
  examples/stdlib/test/test.check
  examples/stdlib/test/test.effekt
  libraries/common/test.effekt
Labels: bug

#487 Allow passing command line parameters directly
  effekt/jvm/src/main/scala/effekt/EffektConfig.scala
  effekt/jvm/src/main/scala/effekt/Runner.scala
Labels: feature, quality-of-life

#489 Standardize command-line argument passing across backends
  effekt/jvm/src/main/scala/effekt/Runner.scala
  libraries/common/args.effekt
Labels: quality-of-life

#490 Implement equality/inequality for `Double`
  libraries/common/effekt.effekt
Labels: feature, area:stdlib

#509 Improve readability of generated LLVM code
  effekt/shared/src/main/scala/effekt/generator/llvm/Transformer.scala
  effekt/shared/src/main/scala/effekt/machine/Transformer.scala
  libraries/common/effekt.effekt
  libraries/llvm/ref.c
  libraries/llvm/rts.ll
Labels: area:llvm, area:machine, requires-design
