Repository effekt-lang/effekt, pull requests merged in 2024-10, with the labels that each got.

#542 Prettify the stdlib testing framework
  effekt/jvm/src/test/scala/effekt/StdlibTests.scala
  examples/pos/lib_test.check
  examples/stdlib/test/fail.check
  examples/stdlib/test/fail.effekt
  examples/stdlib/test/pass.check
  examples/stdlib/test/pass.effekt
  examples/stdlib/test/test.check
  libraries/common/bench.effekt
  libraries/common/string.effekt
  libraries/common/string/tty.effekt
  libraries/common/test.effekt
Labels: area:stdlib, area:tests

#629 Add arithmetic right shift to stdlib
  examples/pos/bitshifts.check
  examples/pos/bitshifts.effekt
  libraries/common/effekt.effekt
Labels: area:stdlib

#622 Improve handling of (unicode) escapes
  effekt/jvm/src/test/scala/effekt/LexerTests.scala
  effekt/shared/src/main/scala/effekt/Lexer.scala
  effekt/shared/src/main/scala/effekt/RecursiveDescent.scala
  effekt/shared/src/main/scala/effekt/generator/chez/Transformer.scala
  effekt/shared/src/main/scala/effekt/generator/chez/package.scala
  examples/pos/unicode_escapes.check
  examples/pos/unicode_escapes.effekt
Labels: bug

#628 Migrate doc comments to use '///'
  libraries/common/array.effekt
  libraries/common/bench.effekt
  libraries/common/buffer.effekt
  libraries/common/bytes.effekt
  libraries/common/dequeue.effekt
  libraries/common/effekt.effekt
  libraries/common/io/console.effekt
  libraries/common/io/error.effekt
  libraries/common/io/filesystem.effekt
  libraries/common/list.effekt
  libraries/common/queue.effekt
  libraries/common/ref.effekt
  libraries/common/result.effekt
  libraries/common/seq.effekt
  libraries/common/string.effekt
Labels: documentation

#619 Js cps backend
  effekt/js/src/main/scala/effekt/LanguageServer.scala
  effekt/js/src/test/scala/effekt/WebTests.scala
  effekt/jvm/src/test/scala/effekt/JavaScriptTests.scala
  effekt/jvm/src/test/scala/effekt/StdlibTests.scala
  effekt/shared/src/main/scala/effekt/Compiler.scala
  effekt/shared/src/main/scala/effekt/Parser.scala
  effekt/shared/src/main/scala/effekt/Typer.scala
  effekt/shared/src/main/scala/effekt/core/LambdaLifting.scala
  effekt/shared/src/main/scala/effekt/core/Tree.scala
  effekt/shared/src/main/scala/effekt/cps/Transformer.scala
  effekt/shared/src/main/scala/effekt/cps/Tree.scala
  effekt/shared/src/main/scala/effekt/generator/js/JavaScript.scala
  effekt/shared/src/main/scala/effekt/generator/js/PrettyPrinter.scala
  effekt/shared/src/main/scala/effekt/generator/js/Transformer.scala
  effekt/shared/src/main/scala/effekt/generator/js/TransformerCps.scala
  effekt/shared/src/main/scala/effekt/generator/js/TransformerDirect.scala
  effekt/shared/src/main/scala/effekt/generator/js/TransformerMonadic.scala
  effekt/shared/src/main/scala/effekt/generator/js/Tree.scala
  examples/benchmarks/effect_handlers_bench/nqueens.effekt
  examples/benchmarks/effect_handlers_bench/triples.effekt
  examples/neg/issue50.check
  examples/neg/lambdas/capability_closure.check
  examples/neg/lambdas/closure.check
  examples/neg/lambdas/continuations.check
  examples/neg/lambdas/simpleescape.check
  examples/neg/object/obj_bidir_boxed.check
  examples/pos/unsafe_cont.check
  examples/pos/unsafe_cont.effekt
  examples/tour/IO.effekt.md
  libraries/common/io.effekt
  libraries/common/io/console.effekt
  libraries/common/io/filesystem.effekt
  libraries/common/io/network.effekt
  libraries/common/io/time.effekt
  libraries/js/effekt_builtins.js
  libraries/js/effekt_runtime.js
  libraries/js/unsafe/cont.effekt
Labels: area:js, experiment

#630 Mutable bytearrays
  effekt/jvm/src/test/scala/effekt/StdlibTests.scala
  effekt/shared/src/main/scala/effekt/generator/llvm/Transformer.scala
  examples/stdlib/bytearray/bytearray.check
  examples/stdlib/bytearray/bytearray.effekt
  examples/stdlib/bytes/bytes.check
  examples/stdlib/bytes/bytes.effekt
  libraries/common/bytearray.effekt
  libraries/common/bytes.effekt
  libraries/common/effekt.effekt
  libraries/common/io/filesystem.effekt
  libraries/common/io/network.effekt
  libraries/common/ref.effekt
  libraries/common/string.effekt
  libraries/llvm/buffer.c
  libraries/llvm/bytearray.c
  libraries/llvm/forward-declare-c.ll
  libraries/llvm/io.c
  libraries/llvm/main.c
  libraries/llvm/types.c
Labels: area:llvm, area:stdlib

#655 Do polymorphism boxing for the result of regions
  effekt/shared/src/main/scala/effekt/core/PolymorphismBoxing.scala
Labels: area:llvm
