Repository effekt-lang/effekt, pull requests merged in 2024-08, with the labels that each got.

#530 LLVM: Pass stack instead of stack pointer
  effekt/shared/src/main/scala/effekt/generator/llvm/Transformer.scala
  libraries/llvm/rts.ll
Labels: area:llvm

#541 Add 'process' module with 'exit' function
  libraries/common/process.effekt
  libraries/common/test.effekt
Labels: feature, area:stdlib

#556 Add `--version` CLI flag
  effekt/jvm/src/main/scala/effekt/EffektConfig.scala
Labels: feature
