Repository effekt-lang/effekt, pull requests merged in 2025-05, with the labels that each got.

#970 Fix generic equals on Chez (#429)
  effekt/jvm/src/test/scala/effekt/ChezSchemeTests.scala
  examples/pos/issue429.check
  examples/pos/issue429.effekt
  libraries/chez/common/effekt_primitives.ss
  libraries/common/effekt.effekt
Labels: area:stdlib, area:chez

#535 Cleanup for #531
  effekt/shared/src/main/scala/effekt/generator/js/PrettyPrinter.scala
  libraries/common/effekt.effekt
Labels: area:js

#974 Taylor series using streams
  examples/stdlib/stream/taylor.check
  examples/stdlib/stream/taylor.effekt
Labels: area:stdlib, area:tests

#922 Stdlib: `tee` for `emit`-streams
  examples/stdlib/stream/tee.check
  examples/stdlib/stream/tee.effekt
  libraries/common/stream.effekt
Labels: area:stdlib

#947 Kindless on the Surface, but kind(ed) in the Core, symbolically: Better, recoverable error messages for wrong kinds
  effekt/jvm/src/test/scala/effekt/RecursiveDescentTests.scala
  effekt/shared/src/main/scala/effekt/Namer.scala
  effekt/shared/src/main/scala/effekt/RecursiveDescent.scala
  effekt/shared/src/main/scala/effekt/Typer.scala
  effekt/shared/src/main/scala/effekt/core/Transformer.scala
  effekt/shared/src/main/scala/effekt/source/Tree.scala
  effekt/shared/src/main/scala/effekt/symbols/TypePrinter.scala
  effekt/shared/src/main/scala/effekt/symbols/kinds.scala
  effekt/shared/src/main/scala/effekt/symbols/symbols.scala
  examples/neg/namer/types/box-as-block-param.check
  examples/neg/namer/types/box-as-block-param.effekt
  examples/neg/namer/types/function-as-paren-param.check
  examples/neg/namer/types/function-as-paren-param.effekt
  examples/neg/namer/types/function-in-record.check
  examples/neg/namer/types/function-in-record.effekt
  examples/neg/namer/types/wrong-order-box-eff.check
  examples/neg/namer/types/wrong-order-box-eff.effekt
  examples/neg/parsing/blockargs.check
Labels: area:compiler, area:parser/lexer

#964 LLVM: Add LTO
  effekt/jvm/src/main/scala/effekt/EffektConfig.scala
  effekt/jvm/src/main/scala/effekt/Runner.scala
Labels: area:llvm

#991 Improve compiler debugging by adding show method to most core trees/types
  effekt/shared/src/main/scala/effekt/core/Tree.scala
  effekt/shared/src/main/scala/effekt/core/Type.scala
Labels: quality-of-life

#986 Add `padLeft`/`padRight` on `String`s
  examples/stdlib/string/strings.check
  examples/stdlib/string/strings.effekt
  libraries/common/string.effekt
Labels: feature, area:stdlib

#993 Prefer versioned executables over generic ones on LLVM
  effekt/jvm/src/main/scala/effekt/Runner.scala
Labels: area:llvm

#988 Add 'char' into prelude
  effekt/js/src/main/scala/effekt/EffektConfig.scala
  effekt/jvm/src/main/scala/effekt/Runner.scala
  effekt/jvm/src/test/scala/effekt/LSPTests.scala
  effekt/jvm/src/test/scala/effekt/core/VMTests.scala
  examples/benchmarks/input_output/financial_format.effekt
  examples/benchmarks/input_output/word_count_utf8.effekt
  examples/stdlib/io/filesystem/wordcount.effekt
  libraries/common/char.effekt
  libraries/common/json.effekt
  libraries/common/result.effekt
  libraries/common/scanner.effekt
  libraries/common/string.effekt
Labels: area:stdlib

#999 Add DIY Binder example
  effekt/jvm/src/test/scala/effekt/core/VMTests.scala
  examples/pos/diy_binder.check
  examples/pos/diy_binder.effekt
Labels: optimizer-wishlist

#1018 Set locale when handrolling JSON
  effekt/shared/src/main/scala/effekt/util/Timer.scala
Labels: quality-of-life

#1019 Add trailing unit to stmts on unexpected end
  effekt/shared/src/main/scala/effekt/RecursiveDescent.scala
Labels: area:parser/lexer
